ERROR en Target=HD154892  Filter=sdss u
Traceback (most recent call last):
  File "c:\Users\Oscar Mellizo\Documents\Mestria Astronomia\TFM\SPA\BeX-Analysis-TFM\run_complete_night.py", line 28, in <module>
    image_paths, polar, wcs, enriched = run_complete_polarimetric_pipeline(
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Mellizo\AppData\Local\Programs\Python\Python311\Lib\site-packages\StellarPolAnalyzer\pipeline.py", line 278, in run_complete_polarimetric_pipeline
    wcs, enriched = annotate_with_astrometry_net(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Mellizo\AppData\Local\Programs\Python\Python311\Lib\site-packages\StellarPolAnalyzer\astrometry.py", line 127, in annotate_with_astrometry_net
    sol = ast.solve_from_image(synthetic_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Mellizo\AppData\Local\Programs\Python\Python311\Lib\site-packages\astroquery\astrometry_net\core.py", line 436, in solve_from_image
    print('Found {} sources'.format(len(sources)), flush=True)
                                    ^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

--------------------------------------------------------------------------------
